- name: get git-prompt
  get_url:
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
    dest: ~/.git-prompt.sh
    mode: 0755

- name: get git-completion
  get_url:
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash
    dest: ~/.git-completion.bash
    mode: 0755

- name: add .bashrc
  lineinfile:
    dest=~/.bashrc
    line={{ item }}
  with_items:
    - source ~/.git-completion.bash
    - source ~/.git-prompt.sh
    - PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '
