- name: get git-prompt
  get_url:
    url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
    dest: ~/.git-prompt.sh
    mode: 0755
    checksum: 'sha256:499c10d259e02cd45e5d1e3d5e1f8fab2b93912d79b90950e15275f72c166611'

- name: add .bashrc
  lineinfile:
    dest=~/.bashrc
    line={{ item }}
  with_items:
    - source ~/.git-prompt.sh
    - PS1='[\u@\h \W$(__git_ps1 " (%s)")]\$ '
