- name: install rpm for rabbitmq for CentOS6.x
  yum:
    name: https://www.rabbitmq.com/releases/rabbitmq-server/v3.6.9/rabbitmq-server-3.6.9-1.el6.noarch.rpm
    state: present
  when: ansible_distribution_version | match('^6\.[0-9]+')

- name: install rpm for rabbitmq for CentOS7.x
  yum:
    name: https://www.rabbitmq.com/releases/rabbitmq-server/v3.6.9/rabbitmq-server-3.6.9-1.el7.noarch.rpm
    state: present
  when: ansible_distribution_version | match('^7\.[0-9]+')

- name: clone tls-gen
  git:
    repo: https://github.com/michaelklishin/tls-gen.git
    dest: /opt/tls-gen
    update: yes

- name: regist stat
  stat:
    path: /opt/tls-gen/basic/result
  register: st

- name: create Certificate
  make:
    chdir: /opt/tls-gen/basic
    target: gen
    params:
      PASSWORD: 'test'
  environment:
    PATH: /root/.anyenv/envs/pyenv/shims:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
  when: st.stat.isdir is not defined
