- name: check anyenv
  stat:
    path: ~/.anyenv
  register: st

- name: clone anyenv
  git: 
    repo: https://github.com/riywo/anyenv.git
    dest: ~/.anyenv
  when: st.stat.isdir is not defined

- name: append enviroment variable
  lineinfile:
    dest=~/.bash_profile
    line={{ item }}
  with_items:
    - 'export PATH="$HOME/.anyenv/bin:$PATH"'
    - 'eval "$(anyenv init -)"'

- name: check pyevn
  stat:
    path: ~/.anyenv/envs/pyenv
  register: st

- name : install pyenv
  environment:
    PATH: "{{ ansible_env.HOME }}/.anyenv/bin:{{ ansible_env.PATH }}"
  shell: anyenv install pyenv
  when: st.stat.isdir is not defined

- name: check python
  stat:
    path: ~/.anyenv/envs/pyenv/versions/{{ python_version }}
  register: st

- name : install python
  environment:
    PATH: "{{ ansible_env.HOME }}/.anyenv/bin:{{ ansible_env.PATH }}"
  shell: eval "$(anyenv init -)" && pyenv install {{ python_version }} && pyenv global {{ python_version }}
  when: st.stat.isdir is not defined

- name: check rbenv
  stat:
    path: ~/.anyenv/envs/rbenv
  register: st

- name: install rbenv
  environment:
    PATH: "{{ ansible_env.HOME }}/.anyenv/bin:{{ ansible_env.PATH }}"
  shell: anyenv install rbenv
  when: st.stat.isdir is not defined

- name: check ruby
  stat:
    path: ~/.anyenv/envs/rbenv/versions/{{ ruby_version }}
  register: st

- name : install ruby
  environment:
    PATH: "{{ ansible_env.HOME }}/.anyenv/bin:{{ ansible_env.PATH }}"
  shell: eval "$(anyenv init -)" && rbenv install {{ ruby_version }} && rbenv global {{ ruby_version }}
  when: st.stat.isdir is not defined

- name: check goenv
  stat:
    path: ~/.anyenv/envs/goenv
  register: st

- name: install goenv
  environment:
    PATH: "{{ ansible_env.HOME }}/.anyenv/bin:{{ ansible_env.PATH }}"
  shell: anyenv install goenv
  when: st.stat.isdir is not defined

- name: check go
  stat:
    path: ~/.anyenv/envs/goenv/versions/{{ go_version }}
  register: st

- name : install go
  environment:
    PATH: "{{ ansible_env.HOME }}/.anyenv/bin:{{ ansible_env.PATH }}"
  shell: eval "$(anyenv init -)" && goenv install {{ go_version }} && goenv global {{ go_version }}
  when: st.stat.isdir is not defined
