- name: install anyenv
  git: 
    repo: https://github.com/riywo/anyenv.git
    dest: ~/.anyenv

- name: append enviroment variable
  lineinfile:
    dest=~/.bash_profile
    line={{ item }}
  with_items:
    - 'export PATH="$HOME/.anyenv/bin:$PATH"'
    - 'eval "$(anyenv init -)"'

- name: initilize anyenv
  environment:
    PATH: "{{ ansible_env.HOME }}/.anyenv/bin:{{ ansible_env.PATH }}"
  shell: >
    eval "$(anyenv init -)"
    creates={{ ansible_env.HOME }}/.anyenv/envs

- name: install envs
  environment:
    PATH: "{{ ansible_env.HOME }}/.anyenv/bin:{{ ansible_env.PATH }}"
  shell: >
    anyenv install {{ item }}
    creates={{ ansible_env.HOME }}/.anyenv/envs/{{ item }}
  with_items:
    - 'goenv'
    - 'pyenv'
    - 'rbenv'

- name : install go
  shell: >
    bash -lc 'goenv install {{ go_version }} && goenv global {{ go_version }}'
    creates={{ ansible_env.HOME }}/.anyenv/envs/goenv/versions/{{ go_version }}

- name : install python
  shell: >
    bash -lc 'pyenv install {{ python_version }} && pyenv global {{ python_version }}'
    creates={{ ansible_env.HOME }}/.anyenv/envs/pyenv/versions/{{ python_version }}

- name : install ruby
  shell: >
    bash -lc 'rbenv install {{ ruby_version }} && rbenv global {{ ruby_version }}'
    creates={{ ansible_env.HOME }}/.anyenv/envs/rbenv/versions/{{ ruby_version }}
