- name: debug
  debug: msg='{{ ansible_os_family }} {{ ansible_distribution_version }}'

- name: centos6.*
  debug: msg={{ ansible_distribution_version }}
  when: ansible_distribution_version | match('^6\.[0-9]+')

- name: centos7.*
  debug: msg={{ ansible_distribution_version }}
  when: ansible_distribution_version | match('^7.[0-9]+')
